### ISSUE TITLE
How do we matching images?

### ISSUE THREAD

**Issue by nsanden** [nsanden/copycatcher#2]
@jmpueblo 

So I spoke to the people at TinEye (the API I wanted to use to make this all work) and also signed up and played around with their API today to see if it would work for us.

The results are promising but it seems it lacks one crucial feature we need. Text recognition.

For example, these 2 tests worked great:

Test 1) SUCCESS!
Search: http://vangogh.teespring.com/shirt_pic/1958664/1998164/front.jpg
Match found: http://vangogh.teespring.com/shirt_pic/1915619/1938754/front.jpg

Test 2) SUCCESS!
Search: https://d2v48i7nl75u94.cloudfront.net/uploads/da719996b336896fb77ef1c943e0c520.jpg
Match found: https://d2v48i7nl75u94.cloudfront.net/uploads/a5dbb72f90a86036015ae506d1d09f7a.

However this test could not find a match:

Test 3) FAIL
Search: http://vangogh.teespring.com/shirt_pic/3070162/3517991/front.jpg
Match found: NONE
Expected Match: http://vangogh.teespring.com/shirt_pic/3054958/3499214/front.jpg

It failed because its a different font and different logo. Even though slightly.

So my thinking at this point is we use both! Your text recognition code, if you can finalize it, and TinEye. Combine both results and then we have a pretty strong image recognition software.

Thoughts?

**Comment by jmpueblo** [comment]
@nsanden 

That's right, TinEye does not use texts in images in finding a match, as mentioned in their documentation.

With regards to the idea of combining TinEye with our existing text recognition API, I think there is no straightforward approach because we will then need to go through every image in TinEye index and run our text recognition API against each image (There are currently billions of images in their index).

However, there is an alternative approach, and here is my suggestion:

We could add a new column called "recognized_text" in our already existing image crawler database, and have this column filled up using our text recognition API during the crawl process. We can then use the image crawler database as an alternative source when the TinEye API returns an empty result.

Let me know if that makes sense..

**Comment by nsanden** [comment]
[8:25:45 AM] Nate S.: Well, they had a few different APIs but the API you spoke about (3 billion images) wont work for us. We have to use another one that requires we upload all 1 million of our teeshirt images and then when we search, it just searches those
[8:27:54 AM] Nate S.: maybe we can reduce that to a lot less images, if we only upload shirts with 1 or more sales

Yes, that sounds good. I think we should just start with the text recognition matches, and later add in the TinEye image recognition layer. I know you ran into some obstacles with the text recognition. Can you take another shot at it and get it working, even if it isn't perfect?

Probably the best way to proceed:
1) BeachinSoft API allows for text recognition of an image. You almost have that built already?
2) TeeSpy uses that API and updates its database with the "recognized_text" field each time it scrapes a new shirt (i'll set this part up)
3) We build a basic TeeSpy API which CopyCatcher can use.

The process is then this:
1) User uploads a shirt image into CopyCatcher.
2) We use BeachinSoft API to get the text from it.
3) We search TeeSpy API to see if any matches.
4) We present matches.

**Comment by jmpueblo** [comment]
Yes, our text recognition in BeachinSoft API is already fully functional. It only needs further improvement. I'll proceed to the next steps that you outlined.

**Comment by nsanden** [comment]
I played around (trying a few different images) with actionExtractText and actionExtractTextTest today. Very cool stuff. actionExtractText is exactly what we need (just needs to work better as you said).

**Comment by jmpueblo** [comment]
Initial code update pushed: Added "Image Search" form and initial backend code implementation.

Please run "composer update".

Current progress:

**Searching by Image URL or by Uploading an image are already supported, although there is no actual "search" being performed in the backend yet.

**Text Recognition is already integrated into the backend of CopyCatcher. I updated OcrController.php in https://github.com/nsanden/api (please pull latest code). Needs improvement in text recognition.

**Search result display format is initially implemented. Please ignore the search result grid view, I will replace it with a list view similar to Pinterest search result layout in TeeSpy.

**No search result items are displayed for now since no actual search is being performed in the backend just yet. I'm working on it.

@nsanden : Is there already an existing API within Teespy that we can use for searching images by text? You mentioned that you'll set that part up..

**Comment by nsanden** [comment]
https://teespy.com/api/get-shirts?text=bomb&limit=20

**Comment by jmpueblo** [comment]
@nsanden 

New code update pushed: 'Keyword' search added plus major updates.
